Priit rooden
Kuulike/WAD2022-HWTeamAY pull request #8
Opened 2022-09-30 16:43 UTC by priitro

Index.html ja osaliselt login css

2022-09-30 16:57 UTC, Kuulike requested changes
Jätsin commentid failipõhiselt. Su merge konflikti lahendus tekitas päris palju kasutut koodi vist.

2022-09-30 16:57 UTC, Kuulike commented on index.html
> +    <link rel="stylesheet" href="res/css/loginStyle.css">
miks sa minu lehe stylesheeti kasutad siin endiselt? Järjekorras peaks ka lehe enda stylesheet link olema pärast general stylesheeti.

2022-09-30 16:57 UTC, Kuulike commented on index.html
> +    <!--
üldiselt lõpuks võiks kõik html commentid ära koristada. HTML commentid jäävad inspect aknas veebibrauseris näha ja see pole üldse ilus

2022-09-30 16:57 UTC, Kuulike commented on res/css/loginStyle.css
> +*{
tundub et sa merge konfliktis kirjutasid mu välja võetud general style optionid tagasi mu loginstyle cssi

2022-09-30 16:57 UTC, Kuulike commented on res/css/style.css
> +    font-family: Times New Roman;
lepime vast kokku ühes fontis üle kogu lehtede grupi ja hoiame seda seadet general styles

2022-09-30 16:57 UTC, Kuulike commented on res/css/style.css
> +.header {
generalstyle cssis on kõik need headeri settingud juba olemas ja pole vaja dubleerida

2022-09-30 17:03 UTC, priitro commented on index.html
> +    <!--
Kommentaarid koristab lõpus ära.

2022-10-05 13:26 UTC, Kuulike approved these changes

2022-10-05 13:27 UTC, Kuulike commented on res/css/style.css
> +.header {
fixed

2022-10-05 13:27 UTC, Kuulike commented on res/css/style.css
> +    font-family: Times New Roman;
fixed

2022-10-05 13:27 UTC, Kuulike commented on res/css/loginStyle.css
> +*{
fixed

2022-10-05 13:27 UTC, Kuulike commented on index.html
> +    <link rel="stylesheet" href="res/css/loginStyle.css">
fixed

2022-10-05 13:27 UTC, merged